language: c

sudo: required

dist: trusty

env:
  matrix:
    - DISTRO=ubuntu
    - DISTRO=ubuntu COVERAGE=ON SONARQUBE=ON
    
addons:
sonarcloud:
  organization: "laurelmcintyre-github"

script:
  - clang -coverage -O0 helloworld.c -o hello
  - ./hello
  - gcov helloworld.c
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)

compiler:
  - gcc
  - clang
