language: c

sudo: required

dist: trusty

env:
  matrix:
    - DISTRO=ubuntu COVERAGE=ON
    
addons:
sonarcloud:
  organization: "laurelmcintyre-github"

script:
  - gcc helloworld.c -o hello
  - coverage run helloworld.c
  - codecov
  - sonar-scanner
    
after_success:
  - bash <(curl -s https://codecov.io/bash)

compiler:
  - gcc
  - clang
