language: c

sudo: required

dist: trusty

env:
  global:
    - GH_REPO_NAME: c
    - DOXYFILE: $TRAVIS_BUILD_DIR/DOXYFILE
    - GH_REPO_REF: github.com/laurelmcintyre/c.git

addons:
  sonarcloud:
    organization: "laurelmcintyre-github"
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

deploy:
  provider: doxygen
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN 
  on:
    branch: master

before_install:
  - ccache -z

script:
  - ${CC} --coverage -c helloworld.c -o helloworld.o
  - ${CC} --coverage helloworld.o -o helloworld
  - ./helloworld
  - sonar-scanner
  
compiler:
  - gcc
  - clang

after_success:
  - ccache -s
  - bash <(curl -s https://codecov.io/bash)
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh

cache:
  ccache: true
  directories:
    - $HOME/.sonar
