language: c

sudo: required

dist: trusty

env:
  matrix:
    - DISTRO=ubuntu COVERAGE=ON
    
addons:
  sonarqube:
    organization: "laurelmcintyre-github"

script:
  - clang -coverage -O0 helloworld.c -o hello
  - ./hello
  - gcc helloworld.c -o hello
  - sonar-scanner 

after_success:
  - bash <(curl -s https://codecov.io/bash)

compiler:
  - gcc
  - clang
