language: c

sudo: required

dist: trusty

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_NAME: c
    - DOXYFILE: $TRAVIS_BUILD_DIR/DOXYFILE
    - GH_REPO_REF: github.com/laurelmcintyre/c.git

addons:
  sonarcloud:
    organization: "laurelmcintyre-github"
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - gcc helloworld.c -o hello
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

compiler:
  - gcc
  - clang

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
  - if [[ ${COVERAGE} && ${CC} = gcc ]]; then
      cd $HOME/docker/git-src;
      git fetch origin gh-pages && git checkout -b gh-pages FETCH_HEAD;
      cp /build/doc/html . ;
      mv html/* .;
      rmdir html; 
      git add --all;
      if [[ ${TRAVIS_BRANCH} = master && ${encrypted_2cc9b7dfce26_key} && ${encrypted_2cc9b7dfce26_iv} && ${TRAVIS_PULL_REQUEST} == false ]]; then
        git config --global user.name "Automatic Deployment (Travis CI)";
        git config --global user.email "abc@abc.com";
        git commit -m "Documentation Update";
        openssl aes-256-cbc -K $encrypted_2cc9b7dfce26_key -iv $encrypted_2cc9b7dfce26_iv -in deploy.enc -out ~/.ssh/id_rsa -d;
        chmod 600 ~/.ssh/id_rsa;
        git push git@github.com:${TRAVIS_REPO_SLUG} gh-pages:gh-pages;
      else
        git status;
        git diff --cached --no-color | head -n 500;
      fi;
    fi

cache:
  ccache: true
  directories:
    - $HOME/.sonar
